# -*- coding: utf-8 -*-
"""Projects_Wei.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3rlMOC-rboUeNJIpst-mVprA3Use5V3
"""

import copy
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from utility.step_lr import StepLR
from torch.nn.utils.stateless import functional_call
from torch.utils.data import random_split, DataLoader


def state_dict_diff(state_dict_a, state_dict_b):
    diff = {}
    for key in state_dict_a:
        diff[key] = state_dict_a[key] - state_dict_b.get(key, torch.zeros_like(state_dict_a[key]))
    return diff

def state_dict_linear_combination(baseline, direction_list, coeffs):
    new_state = {}

    for key in baseline:
        if "running_mean" in key or "running_var" in key:
            new_state[key] = baseline[key].clone()
            continue

        update = torch.zeros_like(baseline[key], dtype=torch.float32)
        for a, d in zip(coeffs, direction_list):
            if key in d:
                update += a * d[key].to(dtype=torch.float32)

        new_state[key] = (baseline[key].to(dtype=torch.float32) + update).to(baseline[key].dtype)

    return new_state


def get_dataloaders(batch_size=128, val_split=0.1):
    transform_train = transforms.Compose([
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.247, 0.243, 0.261))
        ])

    transform_test = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.494, 0.485, 0.450), (0.246, 0.242, 0.261))
    ])


    full_trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform_train)
    testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform_test)


    total_train = len(full_trainset)
    val_size = int(total_train * val_split)
    train_size = total_train - val_size
    trainset, valset = random_split(full_trainset, [train_size, val_size])

    trainloader = DataLoader(trainset, batch_size=batch_size, shuffle=True, num_workers=2)
    valloader = DataLoader(valset, batch_size=batch_size, shuffle=False, num_workers=2)
    testloader = DataLoader(testset, batch_size=batch_size, shuffle=False, num_workers=2)

    return trainloader, valloader, testloader


def get_model():
    model = torchvision.models.resnet18(pretrained=False)
    model.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
    model.maxpool = nn.Identity()
    model.fc = nn.Linear(model.fc.in_features, 10)
    return model

# -----------------------------
# Phase 1: Baseline Training & Data Collection
# -----------------------------
def phase1_train(model, trainloader, device, num_epochs=120, lr=0.1, momentum=0.9):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=lr, momentum=momentum, weight_decay=5e-4)
    scheduler = StepLR(optimizer, lr, num_epochs)
    state_init = copy.deepcopy(model.state_dict())

    grad_directions_batches = []
    state_epoch9 = None

    num_batches = len(trainloader)

    for epoch in range(1, num_epochs + 1):
        model.train()
        running_loss = 0.0
        for batch_idx, (inputs, targets) in enumerate(trainloader):
            inputs, targets = inputs.to(device), targets.to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            loss.backward()

            if epoch == 9 and batch_idx >= num_batches - 7:
                grad_snapshot = {}
                for name, param in model.named_parameters():
                    if param.grad is not None:
                        grad_snapshot[name] = param.grad.detach().clone()
                    else:
                        grad_snapshot[name] = torch.zeros_like(param)
                grad_directions_batches.append(grad_snapshot)

            optimizer.step()
            running_loss += loss.item()

        print(f"Epoch {epoch}/{num_epochs} Loss: {running_loss/num_batches:.4f}")

        if epoch == 9:
            state_epoch9 = copy.deepcopy(model.state_dict())

    state_epoch10 = copy.deepcopy(model.state_dict())
    d1 = state_dict_diff(state_epoch10, state_init)
    d2 = state_dict_diff(state_epoch10, state_epoch9)
    d3 = {}
    for name, param in model.named_parameters():
        state = optimizer.state.get(param, {})
        if 'momentum_buffer' in state:
            d3[name] = state['momentum_buffer'].detach().clone()
        else:
            d3[name] = torch.zeros_like(param)

    d4_to_d10 = grad_directions_batches
    stored_directions = [d1, d2, d3] + d4_to_d10

    return state_epoch10, stored_directions

# -----------------------------
# Phase 2: Extrapolation Training
# -----------------------------

# add extrapolated weights into the parameters
def phase2_extrapolation(model, valloader, device, baseline_state, stored_directions, num_epochs=1, lr_aux=1e-2):

    aux_params = torch.nn.Parameter(torch.randn(10, device=device) * 0.01) #create a parameter object with 10 random scalars
    optimizer_aux = optim.Adam([aux_params], lr=lr_aux)# apply them to optimizer
    criterion = nn.CrossEntropyLoss()
    aux_history = []
    model.eval()

    for epoch in range(num_epochs):
        running_loss = 0.0
        total = 0
        correct = 0

        for batch_idx, (inputs, targets) in enumerate(valloader):
            inputs, targets = inputs.to(device), targets.to(device)

            optimizer_aux.zero_grad()
            # extrapolated parameter：θ_extrapolated = baseline_state + Σ a_i * d_i, Implements the Formula
            extrapolated_state = state_dict_linear_combination(baseline_state, stored_directions, aux_params)

            outputs = functional_call(model, extrapolated_state, (inputs,))
            loss = criterion(outputs, targets)
            loss.backward()
            optimizer_aux.step()

            running_loss += loss.item()
            _, predicted = outputs.max(1)
            total += targets.size(0)
            correct += predicted.eq(targets).sum().item()

        acc = 100. * correct / total
        print(f"[Extrapolation Epoch {epoch+1}] Loss: {running_loss/len(valloader):.4f} | Acc: {acc:.2f}%")
        aux_history.append(aux_params.detach().cpu().clone())

    return aux_params, aux_history

# -----------------------------
# Evaluation function on test set using extrapolated weights
# -----------------------------
def evaluate_extrapolated(model, testloader, device, baseline_state, stored_directions, aux_params):
    model.eval()
    total = 0
    correct = 0
    with torch.no_grad():
        extrapolated_state = state_dict_linear_combination(baseline_state, stored_directions, aux_params)
        for batch_idx, (inputs, targets) in enumerate(testloader):
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = functional_call(model, extrapolated_state, (inputs,))
            _, predicted = outputs.max(1)
            total += targets.size(0)
            correct += predicted.eq(targets).sum().item()
    acc = 100. * correct / total
    print(f"Final Extrapolated Model Accuracy on Test Set: {acc:.2f}%")
    return acc


def main():
    trainloader, valloader, testloader = get_dataloaders(batch_size=128, val_split=0.1)
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

    model = get_model().to(device)

    print("=== Phase 1: Baseline Training (Epochs 1-10) ===")
    baseline_state, stored_directions = phase1_train(model, trainloader, device, num_epochs=10, lr=0.1, momentum=0.9)

    print("\n=== Phase 2: Extrapolation Training (Epoch 11) using Validation Set ===")
    aux_params, aux_history = phase2_extrapolation(model, valloader, device, baseline_state, stored_directions, num_epochs=1, lr_aux=1e-2)

    print("\n=== Final Evaluation on Test Set ===")
    evaluate_extrapolated(model, testloader, device, baseline_state, stored_directions, aux_params)


if __name__ == "__main__":
    main()

aux_params