# -*- coding: utf-8 -*-
"""Projects_Wei.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3rlMOC-rboUeNJIpst-mVprA3Use5V3
"""

import copy
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from utility.step_lr import StepLR
from torch.nn.utils.stateless import functional_call
from torch.utils.data import random_split, DataLoader


def state_dict_diff(state_dict_a, state_dict_b):
    diff = {}
    for key in state_dict_a:
        diff[key] = state_dict_a[key] - state_dict_b.get(key, torch.zeros_like(state_dict_a[key]))
    return diff

def state_dict_linear_combination(baseline, direction_list, coeffs):
    new_state = {}

    for key in baseline:
        if "running_mean" in key or "running_var" in key:
            new_state[key] = baseline[key].clone()
            continue

        update = torch.zeros_like(baseline[key], dtype=torch.float32)
        for a, d in zip(coeffs, direction_list):
            if key in d:
                update += a * d[key].to(dtype=torch.float32)/ len(direction_list) #normalization
                
        new_state[key] = (baseline[key].to(dtype=torch.float32) + update).to(baseline[key].dtype)

    return new_state


def get_dataloaders(batch_size=128, val_split=0.1):
    transform_train = transforms.Compose([
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.247, 0.243, 0.261))
        ])

    transform_test = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.494, 0.485, 0.450), (0.246, 0.242, 0.261))
    ])


    full_trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform_train)
    testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform_test)


    total_train = len(full_trainset)
    val_size = int(total_train * val_split)
    train_size = total_train - val_size
    trainset, valset = random_split(full_trainset, [train_size, val_size])

    trainloader = DataLoader(trainset, batch_size=batch_size, shuffle=True, num_workers=2)
    valloader = DataLoader(valset, batch_size=batch_size, shuffle=False, num_workers=2)
    testloader = DataLoader(testset, batch_size=batch_size, shuffle=False, num_workers=2)

    return trainloader, valloader, testloader


def get_model():
    model = torchvision.models.resnet18(pretrained=False)
    model.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
    model.maxpool = nn.Identity()
    model.fc = nn.Linear(model.fc.in_features, 10)
    return model

# -----------------------------
# Phase 1: Baseline Training & Data Collection
# -----------------------------
def phase1_train(model, trainloader, device, num_epochs=120, lr=0.1, momentum=0.9,
                 epoch_offsets=[2, 3, 4, 5, 10, 20, 30, 50, 80]):

    epoch_offsets+= epoch_offsets + [num_epochs-1,num_epochs-2]
    criterion = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=lr, momentum=momentum, weight_decay=5e-4)
    # Assuming your custom StepLR is defined to be called once per epoch
    scheduler = StepLR(optimizer, lr, num_epochs)  
    state_init = copy.deepcopy(model.state_dict())

    # Determine which epochs to save states from.
    # Always include the first epoch.
    desired_epoch_indices = set([1])
    for offset in epoch_offsets:
        epoch_idx = num_epochs - offset
        if epoch_idx >= 1:
            desired_epoch_indices.add(epoch_idx)
    desired_epoch_indices = sorted(desired_epoch_indices)
    
    saved_epoch_states = {}           # key: epoch number, value: state dict
    grad_directions_last_epoch_batches = []  # list to collect gradients for each batch in the final epoch
    num_batches = len(trainloader)
    
    for epoch in range(1, num_epochs + 1):
        model.train()
        running_loss = 0.0
        
        for batch_idx, (inputs, targets) in enumerate(trainloader):
            inputs, targets = inputs.to(device), targets.to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            loss.backward()

            
            running_loss += loss.item()
            
            # If we're in the final epoch, record gradients for every batch.
            if epoch == num_epochs and batch_idx> num_batches-7:
                grad_snapshot = {}
                for name, param in model.named_parameters():
                    if param.grad is not None:
                        grad_snapshot[name] = param.grad.detach().clone()
                    else:
                        grad_snapshot[name] = torch.zeros_like(param)
                grad_directions_last_epoch_batches.append(grad_snapshot)
            #else: 
            optimizer.step()
        # Save the model state at epochs we desire.
        if epoch in desired_epoch_indices:
            saved_epoch_states[epoch] = copy.deepcopy(model.state_dict())
        
        # Step the scheduler once per epoch (ensure your StepLR is designed for this)
        scheduler(epoch)
        print(f"Epoch {epoch}/{num_epochs} Loss: {running_loss/num_batches:.4f}")
    
    final_state = copy.deepcopy(model.state_dict())
    
    # Compute epoch-level directions: the difference between the final state and each saved state.
    epoch_level_directions = []
    for epoch in desired_epoch_indices:
        direction = state_dict_diff(final_state, saved_epoch_states[epoch])
        epoch_level_directions.append(direction)
    
    # Capture the momentum buffer as a separate direction.
    momentum_buffer_direction = {}
    for name, param in model.named_parameters():
        state = optimizer.state.get(param, {})
        if 'momentum_buffer' in state:
            momentum_buffer_direction[name] = state['momentum_buffer'].detach().clone()
        else:
            momentum_buffer_direction[name] = torch.zeros_like(param)
    
    # Combine all directions.
    stored_directions = epoch_level_directions + [momentum_buffer_direction] + grad_directions_last_epoch_batches
    total_directions = len(stored_directions)
    print(f"Total directions saved: {total_directions}")
    
    return final_state, stored_directions


# -----------------------------
# Phase 2: Extrapolation Training
# -----------------------------

def periodic_extrapolation_training(model, valloader, device, baseline_state, stored_directions, num_rounds=5, n_epochs_per_round=1, lr_aux=1e-2):

    criterion = nn.CrossEntropyLoss()

    # Initialize raw auxiliary parameters
    aux_params_raw = torch.nn.Parameter(
        torch.randn(len(stored_directions), device=device)
    )
    
    optimizer_aux = optim.Adam([aux_params_raw], lr=lr_aux, weight_decay=1e-3)

    for round_idx in range(num_rounds):
        # Initialize auxiliary parameters uniformly between -1 and 1.
                
        print(f"\n=== Extrapolation Round {round_idx+1} ===")
        for epoch in range(n_epochs_per_round):
            model.eval()  # keep the model in eval mode for the functional call
            running_loss = 0.0
            total = 0
            correct = 0
            
            for inputs, targets in valloader:
                inputs, targets = inputs.to(device), targets.to(device)
                optimizer_aux.zero_grad()
                
                # Gradients flow through this transformation.
                aux_params = torch.tanh(aux_params_raw)
                #aux_params = torch.sigmoid(aux_params_raw) #lets try sig because non negative is more stable
                # Compute the extrapolated state using current aux_params.
                extrapolated_state = state_dict_linear_combination(baseline_state, stored_directions, aux_params)
                outputs = functional_call(model, extrapolated_state, (inputs,))
                loss = criterion(outputs, targets)
                loss.backward()
                optimizer_aux.step()
                
                running_loss += loss.item()
                _, predicted = outputs.max(1)
                total += targets.size(0)
                correct += predicted.eq(targets).sum().item()
            
            acc = 100. * correct / total
            print(f"Round {round_idx+1}, Epoch {epoch+1}: Loss: {running_loss/len(valloader):.4f} | Acc: {acc:.2f}%")
        print(aux_params_raw)
        # After n_epochs_per_round, update the baseline with the extrapolated weights.
        new_extrapolated_state = state_dict_linear_combination(baseline_state, stored_directions, aux_params)
        # Load the new state into the model.
        model.load_state_dict(new_extrapolated_state)
        # Update the baseline state for future rounds.
        baseline_state = {k: v.clone().detach() for k, v in new_extrapolated_state.items()}
        print(f"Baseline updated after Round {round_idx+1}.\n")
    
    return baseline_state

def evaluate_baseline(model, dataloader, device, baseline_state, dataset_name="dataset"):
    """
    Evaluates the baseline model (using baseline_state) on the given dataloader.
    Returns the accuracy and average loss.
    """
    model.eval()
    total = 0
    correct = 0
    running_loss = 0.0
    criterion = nn.CrossEntropyLoss()
    
    with torch.no_grad():
        for batch_idx, (inputs, targets) in enumerate(dataloader):
            inputs, targets = inputs.to(device), targets.to(device)
            # Use the baseline state for a functional forward pass.
            outputs = functional_call(model, baseline_state, (inputs,))
            loss = criterion(outputs, targets)
            running_loss += loss.item()
            _, predicted = outputs.max(1)
            total += targets.size(0)
            correct += predicted.eq(targets).sum().item()
    
    avg_loss = running_loss / len(dataloader)
    acc = 100. * correct / total
    print(f"Baseline {dataset_name} --> Accuracy: {acc:.2f}% | Loss: {avg_loss:.4f}")
    return acc, avg_loss

# -----------------------------
# Evaluation function on test set using extrapolated weights
# -----------------------------
def evaluate_extrapolated(model, testloader, device, baseline_state, stored_directions, aux_params):
    model.eval()
    total = 0
    correct = 0
    with torch.no_grad():
        extrapolated_state = state_dict_linear_combination(baseline_state, stored_directions, aux_params)
        for batch_idx, (inputs, targets) in enumerate(testloader):
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = functional_call(model, extrapolated_state, (inputs,))
            _, predicted = outputs.max(1)
            total += targets.size(0)
            correct += predicted.eq(targets).sum().item()
    acc = 100. * correct / total
    print(f"Final Extrapolated Model Accuracy on Test Set: {acc:.2f}%")
    return acc


def main():
    trainloader, valloader, testloader = get_dataloaders(batch_size=128, val_split=0.1)
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

    model = get_model().to(device)

    print("=== Phase 1: Baseline Training (Epochs 1-10) ===")
    baseline_state, stored_directions = phase1_train(model, trainloader, device, num_epochs=10, lr=0.1, momentum=0.9)
    
    print("\n=== Evaluating Baseline Model ===")
    # Evaluate baseline on the validation set.
    evaluate_baseline(model, valloader, device, baseline_state, dataset_name="Validation Set")
    
    # Evaluate baseline on the test set.
    evaluate_baseline(model, testloader, device, baseline_state, dataset_name="Test Set")


    print("\n=== Phase 2: Periodic Extrapolation Training ===")
    # For example, run 5 rounds of 1 epoch each.
    updated_baseline_state = periodic_extrapolation_training(model, valloader, device, baseline_state, stored_directions, num_rounds=2, n_epochs_per_round=1, lr_aux=1e-2)

    print("\n=== Final Evaluation on Test Set with Updated Baseline ===")
    evaluate_extrapolated(model, testloader, device, updated_baseline_state, stored_directions, aux_params=torch.zeros(len(stored_directions), device=device))
    # Note: In the final evaluation here, aux_params is set to zero for simplicity.
    
    #print(aux_params)

if __name__ == "__main__":
    main()